<?xml version="1.0" encoding="utf-8"?><Database Name="SimpleMac" Class="SimpleMacModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\SimpleMac.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="Icodeon.Hotwire.Framework.Properties.Settings" SettingsPropertyName="SimpleMacConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MacSaltHistory" Member="MacSaltHistories">
    <Type Name="MacSaltHistory">
      <Column Name="Salt" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mac" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
</Database>