USE [master]
GO

/****** Object:  Database [HotwireUnitTest]    Script Date: 09/29/2011 17:37:19 ******/
CREATE DATABASE [HotwireUnitTest] 

GO

ALTER DATABASE [HotwireUnitTest] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotwireUnitTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HotwireUnitTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [HotwireUnitTest] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [HotwireUnitTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HotwireUnitTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HotwireUnitTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HotwireUnitTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HotwireUnitTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HotwireUnitTest] SET  READ_WRITE 
GO

ALTER DATABASE [HotwireUnitTest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HotwireUnitTest] SET  MULTI_USER 
GO

ALTER DATABASE [HotwireUnitTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HotwireUnitTest] SET DB_CHAINING OFF 
GO

